version: '3'
services:
    web:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
    db: # phpmyadmin config says by default hostname of database server is 'db'
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - mysqldata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links: 
            - db
        ports:
            - 8001:80
        environment:
            - PMA_ARBITRARY=1
volumes:
    mysqldata: {}



